name: Draft release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Type of release (major,minor,patch)'
        required: true
        default: 'minor'
jobs:
  release-draft:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6

      - name: Install dependencies
        run: npm ci

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Push temporary release branch
        run: |
          git push origin --delete release/tmp | true
          git checkout -b release/tmp
          git push --set-upstream origin release/tmp
          npm run release ${{ github.event.inputs.release }}

      - name: Get version
        run: |
          echo "SERVICE_VERSION=$(cat package.json \
                                          | grep version \
                                          | head -1 \
                                          | awk -F: '{ print $2 }' \
                                          | sed 's/[",]//g' \
                                          | tr -d '[[:space:]]')" >> $GITHUB_ENV

      - name: Create release branch
        run: |
          git push origin --delete release/${{ env.SERVICE_VERSION }} | true
          git checkout -b release/${{ env.SERVICE_VERSION }}
          git push --set-upstream origin release/${{ env.SERVICE_VERSION }}
          git push origin --delete release/tmp | true

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          head: release/${{ env.SERVICE_VERSION }}
          base: master
          title: Release ${{ env.SERVICE_VERSION }}
