name: Build and publish release

on:
  push:
    branches:
      - 'master'
jobs:
  release-build:
    name: Setup-Build-Publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
          registry-url: https://npm.pkg.github.com/

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        run: |
          echo "SERVICE_VERSION=$(cat package.json \
                                          | grep version \
                                          | head -1 \
                                          | awk -F: '{ print $2 }' \
                                          | sed 's/[",]//g' \
                                          | tr -d '[[:space:]]')" >> $GITHUB_ENV

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Push tag
        run: |
          git tag ${{ env.SERVICE_VERSION }}
          git push origin ${{ env.SERVICE_VERSION }}

          git checkout develop
          git merge master -m "Merge master"
          git push --set-upstream origin develop

          git checkout master

      - name: Install dependencies
        run: npm ci

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
